//! Canonical stored assertions, projected co-derivation, and bounded graph
//! algorithms. Structural edges are observed state, never model assertions.
use std::{cmp::Ordering,collections::{BTreeMap,BTreeSet,BinaryHeap,VecDeque}};
use rusqlite::{params,Connection,OptionalExtension,TransactionBehavior};
use serde_json::{json,Value};
use crate::{beliefs,config::Config,gate::Authority,scrub,store,Error,Result};
pub const ASSERTED:&[&str]=&["depends_on","specializes","explains","contradicts","applies_when"];
pub fn symmetric(rel:&str)->bool{matches!(rel,"contradicts"|"co_derived")}
pub fn support_factor(n:u64)->f64{(1.-(-(n as f64)/2.).exp()).min(0.99)}
#[derive(Clone,Debug)]pub struct Edge{pub dst:i64,pub rel:String,pub weight:f64}
pub type Adjacency=BTreeMap<i64,Vec<Edge>>;
pub fn edge_support(conn:&Connection,mut src:i64,mut dst:i64,rel:&str)->Result<u64>{if symmetric(rel)&&src>dst{std::mem::swap(&mut src,&mut dst)}Ok(conn.query_row("SELECT count(DISTINCT session_id) FROM belief_edge_assertions WHERE src=? AND dst=? AND rel=?",params![src,dst,rel],|r|beliefs::sql_count(r,0))?)}
pub(crate) fn edge_insert_in_transaction(cfg:&Config,conn:&Connection,mut src:i64,mut dst:i64,rel:&str,source:&str,sid:Option<&str>,note:Option<&str>,authority:&Authority)->Result<bool>{
    beliefs::require_write(authority)?;
    if src==dst||!(ASSERTED.contains(&rel)||rel=="supersedes"){return Ok(false)}if symmetric(rel)&&src>dst{std::mem::swap(&mut src,&mut dst)}
    let mut stmt=conn.prepare("SELECT id,subject,uid FROM beliefs WHERE id IN (?,?)")?;let rows=stmt.query_map(params![src,dst],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;if rows.len()!=2{return Ok(false)}let by_id:BTreeMap<_,_>=rows.into_iter().map(|(id,s,u)|(id,(s,u))).collect();let now=crate::utcnow();let note=note.map(|s|beliefs::crop(&beliefs::one_line(s),300));
    let created=conn.execute("INSERT OR IGNORE INTO belief_edges(src,dst,rel,source,session_id,note,created) VALUES(?,?,?,?,?,?,?)",params![src,dst,rel,source,sid,note,now])?>0;
    let asserted=if let Some(sid)=sid{conn.execute("INSERT OR IGNORE INTO belief_edge_assertions(src,dst,rel,session_id,created) VALUES(?,?,?,?,?)",params![src,dst,rel,sid,now])?>0}else{false};
    if created||asserted{let pk=beliefs::key(conn,&by_id[&src].0)?;store::append_op(cfg,conn,"belief","edge",pk.as_deref(),&json!({"src_uid":by_id[&src].1,"dst_uid":by_id[&dst].1,"rel":rel,"source":source,"session_id":sid,"note":note}))?}Ok(created)
}
pub(crate) fn repoint(conn:&Connection,old:i64,new:i64)->Result<()>{
    // Normalize symmetric endpoints after replacing either endpoint. Otherwise
    // replacing the lower endpoint with a higher ID silently loses support.
    let mut stmt=conn.prepare("SELECT src,dst,rel,source,session_id,note,created FROM belief_edges WHERE src=? OR dst=?")?;
    let edges=stmt.query_map(params![old,old],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,i64>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?,r.get::<_,Option<String>>(4)?,r.get::<_,Option<String>>(5)?,r.get::<_,Option<String>>(6)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;drop(stmt);
    let mut stmt=conn.prepare("SELECT src,dst,rel,session_id,created FROM belief_edge_assertions WHERE src=? OR dst=?")?;
    let assertions=stmt.query_map(params![old,old],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,i64>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?,r.get::<_,Option<String>>(4)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;drop(stmt);
    conn.execute("DELETE FROM belief_edges WHERE src=? OR dst=?",params![old,old])?;conn.execute("DELETE FROM belief_edge_assertions WHERE src=? OR dst=?",params![old,old])?;
    let endpoints=|src,dst,rel:&str|{let mut a=if src==old{new}else{src};let mut b=if dst==old{new}else{dst};if symmetric(rel)&&a>b{std::mem::swap(&mut a,&mut b)}(a,b)};
    for (src,dst,rel,source,sid,note,created) in edges{let(a,b)=endpoints(src,dst,&rel);if a!=b{conn.execute("INSERT OR IGNORE INTO belief_edges(src,dst,rel,source,session_id,note,created) VALUES(?,?,?,?,?,?,?)",params![a,b,rel,source,sid,note,created])?;}}
    for(src,dst,rel,sid,created) in assertions{let(a,b)=endpoints(src,dst,&rel);if a!=b{conn.execute("INSERT OR IGNORE INTO belief_edge_assertions(src,dst,rel,session_id,created) VALUES(?,?,?,?,?)",params![a,b,rel,sid,created])?;}}Ok(())
}

pub fn adjacency(conn:&Connection,subjects:Option<&[String]>,statuses:&[&str],rels:Option<&BTreeSet<String>>,co_derived:bool)->Result<(Adjacency,BTreeMap<i64,String>)>{
    let mut stmt=conn.prepare("SELECT id,subject,claim,status FROM beliefs ORDER BY id LIMIT 10001")?;
    let rows=stmt.query_map([],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;if rows.len()>10000{return Err(Error::TooLarge)}
    let mut claims=BTreeMap::new();for (id,subject,claim,status) in rows{if statuses.contains(&status.as_str())&&subjects.is_none_or(|s|s.contains(&subject)){claims.insert(id,scrub::scrub(&claim)?);}}
    let mut adj=Adjacency::new();let mut put=|a:i64,b:i64,rel:&str,w:f64|{adj.entry(a).or_default().push(Edge{dst:b,rel:rel.into(),weight:w});if symmetric(rel){adj.entry(b).or_default().push(Edge{dst:a,rel:rel.into(),weight:w});}};
    let mut stmt=conn.prepare("SELECT src,dst,rel,source FROM belief_edges ORDER BY src,dst,rel LIMIT 100001")?;let rows=stmt.query_map([],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,i64>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;if rows.len()>100000{return Err(Error::TooLarge)}
    for (src,dst,rel,source) in rows{if !claims.contains_key(&src)||!claims.contains_key(&dst)||!(ASSERTED.contains(&rel.as_str())||rel=="supersedes")||rels.is_some_and(|rels|!rels.contains(&rel)){continue}let weight=if source=="structural"||rel=="supersedes"{1.}else{support_factor(edge_support(conn,src,dst,&rel)?)};put(src,dst,&rel,weight);}
    if co_derived&&rels.is_none_or(|s|s.contains("co_derived")){
        let mut stmt=conn.prepare("SELECT belief_id,session_id FROM belief_evidence WHERE session_id IS NOT NULL LIMIT 100001")?;let rows=stmt.query_map([],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,String>(1)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;if rows.len()>100000{return Err(Error::TooLarge)}let mut sessions:BTreeMap<String,BTreeSet<i64>>=BTreeMap::new();for (id,sid) in rows{if claims.contains_key(&id){sessions.entry(sid).or_default().insert(id);}}
        for ids in sessions.values().filter(|s|(2..=8).contains(&s.len())){let ids:Vec<_>=ids.iter().copied().collect();for (i,a) in ids.iter().enumerate(){for b in &ids[i+1..]{put(*a,*b,"co_derived",1./ids.len() as f64);}}}
    }Ok((adj,claims))
}
pub fn khop(adj:&Adjacency,start:i64,k:usize,rels:Option<&BTreeSet<String>>)->BTreeMap<i64,usize>{
    let mut seen=BTreeMap::from([(start,0)]);let mut queue=VecDeque::from([(start,0)]);while let Some((node,depth))=queue.pop_front(){if depth==k{continue}for edge in adj.get(&node).into_iter().flatten(){if rels.is_none_or(|s|s.contains(&edge.rel))&&!seen.contains_key(&edge.dst){seen.insert(edge.dst,depth+1);queue.push_back((edge.dst,depth+1));}}}seen
}
#[derive(Clone,Copy)]struct Visit{cost:f64,node:i64}
impl PartialEq for Visit{fn eq(&self,other:&Self)->bool{self.cost==other.cost&&self.node==other.node}}impl Eq for Visit{}
impl PartialOrd for Visit{fn partial_cmp(&self,other:&Self)->Option<Ordering>{Some(self.cmp(other))}}
impl Ord for Visit{fn cmp(&self,other:&Self)->Ordering{other.cost.total_cmp(&self.cost).then_with(||other.node.cmp(&self.node))}}
pub fn best_path(adj:&Adjacency,src:i64,dst:i64,rels:Option<&BTreeSet<String>>)->(Vec<(i64,String,i64)>,f64){
    if src==dst{return (Vec::new(),1.)}let mut dist=BTreeMap::from([(src,0.)]);let mut prev=BTreeMap::new();let mut queue=BinaryHeap::from([Visit{cost:0.,node:src}]);let mut settled=BTreeSet::new();
    while let Some(Visit{cost,node})=queue.pop(){if !settled.insert(node){continue}if node==dst{break}for edge in adj.get(&node).into_iter().flatten(){if rels.is_some_and(|s|!s.contains(&edge.rel)){continue}let next=cost-edge.weight.max(1e-9).ln();if next<*dist.get(&edge.dst).unwrap_or(&f64::INFINITY){dist.insert(edge.dst,next);prev.insert(edge.dst,(node,edge.rel.clone()));queue.push(Visit{cost:next,node:edge.dst});}}}
    let Some(cost)=dist.get(&dst) else{return (Vec::new(),0.)};let mut hops=Vec::new();let mut node=dst;while node!=src{let Some((parent,rel))=prev.get(&node) else{return (Vec::new(),0.)};hops.push((*parent,rel.clone(),node));node=*parent;}hops.reverse();(hops,(-cost).exp())
}
pub fn simple_paths(adj:&Adjacency,src:i64,dst:i64,cutoff:usize,rels:Option<&BTreeSet<String>>,cap:usize)->Result<Vec<Vec<i64>>>{
    if cutoff>8||cap>256{return Err(Error::InvalidRequest)}let mut out=Vec::new();let mut stack=vec![(src,vec![src])];let mut work=0;while let Some((node,path))=stack.pop(){if out.len()>=cap{break}work+=1;if work>100000{return Err(Error::TooLarge)}if path.len()-1>=cutoff{continue}for edge in adj.get(&node).into_iter().flatten(){if path.contains(&edge.dst)||rels.is_some_and(|s|!s.contains(&edge.rel)){continue}let mut next=path.clone();next.push(edge.dst);if edge.dst==dst{out.push(next);if out.len()>=cap{break}}else{stack.push((edge.dst,next));}}}Ok(out)
}
pub fn components(adj:&Adjacency,nodes:&BTreeSet<i64>)->Vec<Vec<i64>>{
    let mut undirected:BTreeMap<i64,BTreeSet<i64>>=BTreeMap::new();for (a,edges) in adj{for edge in edges{if nodes.contains(a)&&nodes.contains(&edge.dst){undirected.entry(*a).or_default().insert(edge.dst);undirected.entry(edge.dst).or_default().insert(*a);}}}let mut seen=BTreeSet::new();let mut groups=Vec::new();for node in nodes{if !seen.insert(*node){continue}let mut group=vec![*node];let mut queue=VecDeque::from([*node]);while let Some(n)=queue.pop_front(){for nb in undirected.get(&n).into_iter().flatten(){if seen.insert(*nb){group.push(*nb);queue.push_back(*nb)}}}group.sort();groups.push(group);}groups.sort_by(|a,b|b.len().cmp(&a.len()).then(a.cmp(b)));groups
}
pub fn communities(adj:&Adjacency,nodes:&BTreeSet<i64>,rounds:usize)->Vec<Vec<i64>>{
    let mut labels:BTreeMap<_,_>=nodes.iter().map(|n|(*n,*n)).collect();let mut order:Vec<_>=nodes.iter().copied().collect();for round in 0..rounds.min(64){if order.is_empty(){break}let k=round%order.len();order.rotate_left(k);let mut moved=false;for node in &order{let mut votes:BTreeMap<i64,f64>=BTreeMap::new();for edge in adj.get(node).into_iter().flatten(){if let Some(label)=labels.get(&edge.dst){*votes.entry(*label).or_default()+=edge.weight;}}if let Some((&top,_))=votes.iter().max_by(|(a,x),(b,y)|x.total_cmp(y).then_with(||b.cmp(a))){if top!=labels[node]{labels.insert(*node,top);moved=true}}}if !moved{break}}let mut grouped:BTreeMap<i64,Vec<i64>>=BTreeMap::new();for (node,label) in labels{grouped.entry(label).or_default().push(node)}let mut groups:Vec<_>=grouped.into_values().collect();groups.sort_by(|a,b|b.len().cmp(&a.len()).then(a.cmp(b)));groups
}
pub fn degree(adj:&Adjacency)->BTreeMap<i64,u64>{let mut out=BTreeMap::new();for (a,edges) in adj{for edge in edges{*out.entry(*a).or_default()+=1;*out.entry(edge.dst).or_default()+=1}}out}
pub fn context_candidates(_cfg:&Config,conn:&Connection,prompt:&str,subjects:&[String],hops:usize)->Result<Vec<Value>>{
    let rels: BTreeSet<String>=ASSERTED.iter().map(|s|(*s).into()).collect();let (adj,claims)=adjacency(conn,Some(subjects),&["active"],Some(&rels),false)?;let expr=crate::index::fts_expr(prompt," OR ");let mut seeds=BTreeMap::new();
    if !expr.is_empty(){let placeholders=vec!["?";subjects.len()].join(",");let sql=format!("SELECT b.id FROM beliefs b JOIN belief_fts f ON b.id=f.belief_id WHERE belief_fts MATCH ? AND status='active' AND subject IN ({placeholders}) ORDER BY bm25(belief_fts) LIMIT 12");let mut values=vec![expr];values.extend_from_slice(subjects);let mut stmt=conn.prepare(&sql)?;for id in stmt.query_map(rusqlite::params_from_iter(values),|r|r.get::<_,i64>(0))?{let id=id?;if claims.contains_key(&id){seeds.insert(id,"match");if seeds.len()==12{break}}}}
    if seeds.is_empty(){let placeholders=vec!["?";subjects.len()].join(",");let sql=format!("SELECT id FROM beliefs WHERE status='active' AND subject IN ({placeholders}) ORDER BY confidence DESC,updated DESC LIMIT 12");let mut stmt=conn.prepare(&sql)?;for id in stmt.query_map(rusqlite::params_from_iter(subjects),|r|r.get::<_,i64>(0))?{let id=id?;if claims.contains_key(&id){seeds.insert(id,"in scope");if seeds.len()==12{break}}}}
    let mut out:BTreeMap<i64,Value>=BTreeMap::new();for (seed,why) in seeds{for (node,depth) in khop(&adj,seed,hops.min(8),Some(&rels)){if out.get(&node).and_then(|v|v["hops"].as_u64()).is_some_and(|old|old<=depth as u64){continue}let (path,path_conf)=if depth==0{(Vec::new(),1.)}else{best_path(&adj,seed,node,Some(&rels))};let via=path.last().map_or(why,|h|h.1.as_str());let conf:f64=conn.query_row("SELECT confidence FROM beliefs WHERE id=?",[node],|r|r.get(0))?;let (c,x,s)=beliefs::outcome_counts(conn,node)?;let calibrated=c+x+s>=3;let base=if calibrated{beliefs::calibrated_confidence(conf,c,x)}else{conf};out.insert(node,json!({"id":node,"hops":depth,"via":via,"path":path_conf,"seed":seed,"claim":claims[&node],"conf":conf,"calibrated":calibrated,"n_out":c+x+s,"score":base*path_conf}));}}
    let mut rows:Vec<_>=out.into_values().collect();rows.sort_by(|a,b|b["calibrated"].as_bool().cmp(&a["calibrated"].as_bool()).then_with(||b["score"].as_f64().unwrap_or(0.).total_cmp(&a["score"].as_f64().unwrap_or(0.))).then_with(||a["claim"].as_str().unwrap_or("").chars().count().cmp(&b["claim"].as_str().unwrap_or("").chars().count())));Ok(rows)
}
fn html_escape(s:&str)->String{s.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;").replace('"',"&quot;").replace('\'',"&#39;")}
pub fn mermaid_source(adj:&Adjacency,claims:&BTreeMap<i64,String>,nodes:&BTreeSet<i64>)->String{
    let mut out=String::from("flowchart LR\n");for id in nodes{out.push_str(&format!("  b{id}[\"<b>{id}</b><br/>{}\"]\n",html_escape(&beliefs::crop(&beliefs::one_line(claims.get(id).map_or("?",String::as_str)),90))));}let mut seen=BTreeSet::new();for src in nodes{for edge in adj.get(src).into_iter().flatten(){if !nodes.contains(&edge.dst){continue}let key=if symmetric(&edge.rel){((*src).min(edge.dst),(*src).max(edge.dst),edge.rel.clone())}else{(*src,edge.dst,edge.rel.clone())};if seen.insert(key){out.push_str(&format!("  b{src} {}|{}| b{}\n",if symmetric(&edge.rel){"---"}else{"-->"},edge.rel,edge.dst));}}}out
}
pub fn read(cfg:&Config,req:&Value)->Result<Value>{
    let scope=beliefs::subjects(req)?;let bid=beliefs::id(req,"belief_id")?;let browser=req["browser"].as_bool().ok_or(Error::InvalidRequest)?;let mut conn=store::connect(cfg)?;let tx=conn.transaction()?;
    let row=tx.query_row("SELECT subject,status FROM beliefs WHERE id=?",[bid],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?))).optional()?.ok_or(Error::Changed)?;if !scope.contains(&row.0)||row.1!="active"{return Err(Error::Changed)}
    let mut lines=Vec::new();for (direction,sql) in [("out","SELECT e.dst,e.rel,e.source,b.claim,b.status,b.subject FROM belief_edges e JOIN beliefs b ON b.id=e.dst WHERE src=? ORDER BY rel,dst"),("in","SELECT e.src,e.rel,e.source,b.claim,b.status,b.subject FROM belief_edges e JOIN beliefs b ON b.id=e.src WHERE dst=? ORDER BY rel,src")]{let mut stmt=tx.prepare(sql)?;for row in stmt.query_map([bid],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?,r.get::<_,String>(4)?,r.get::<_,String>(5)?)))?{let (other,rel,source,claim,status,subject)=row?;if !scope.contains(&subject){continue}let (a,b)=if direction=="out"{(bid,other)}else{(other,bid)};let basis=if source=="structural"{"observed".into()}else{format!("n={}",edge_support(&tx,a,b,&rel)?)};let status=if status=="active"{String::new()}else{format!(", {status}")};let arrow=if direction=="out"{format!("--{rel}-->")}else{format!("<--{rel}--")};let line=scrub::scrub(&format!("    {arrow} [{other}] ({source}, {basis}{status}) {}",beliefs::crop(&beliefs::one_line(&scrub::scrub(&claim)?),120)))?;if line.len()>4096||line.chars().any(char::is_control)||lines.len()==200{return Err(Error::TooLarge)}lines.push(line)}}
    if lines.is_empty(){return Ok(json!({"id":bid,"lines":["No relations recorded in this scope"],"html":null,"note":"No scoped relations"}))}let mut value=json!({"id":bid,"lines":lines,"html":null,"note":"LORE relations · project/user scope"});
    if browser{let (adj,claims)=adjacency(&tx,Some(&scope),&["active"],None,true)?;let nodes:BTreeSet<_>=khop(&adj,bid,2,None).into_keys().collect();if nodes.len()>200{return Err(Error::TooLarge)}let note=format!("belief {bid}, 2 hops · {} beliefs · project/user scope",nodes.len());let html=include_str!("graph_html.html").replace("@TITLE@",&format!("belief {bid}")).replace("@NOTE@",&html_escape(&note)).replace("@GRAPH@",&mermaid_source(&adj,&claims,&nodes));if html.len()>crate::MAX_FRAME_BYTES-512{return Err(Error::TooLarge)}value["html"]=json!(html);value["note"]=json!(note);}Ok(value)
}
pub fn query(cfg:&Config,req:&Value)->Result<Value>{
    let scope=beliefs::subjects(req)?;let conn=store::connect(cfg)?;let (adj,claims)=adjacency(&conn,Some(&scope),&["active"],None,true)?;let nodes=claims.keys().copied().collect();let mode=beliefs::text(req,"mode",32)?;for field in ["belief_id","src","dst"]{if req.get(field).is_some()&&!claims.contains_key(&beliefs::id(req,field)?){return Err(Error::Changed)}}
    match mode{"components"=>Ok(json!(components(&adj,&nodes))),"communities"=>Ok(json!(communities(&adj,&nodes,12))),"degree"=>Ok(json!(degree(&adj))),"khop"=>Ok(json!(khop(&adj,beliefs::id(req,"belief_id")?,req["hops"].as_u64().filter(|n|*n<=8).ok_or(Error::InvalidRequest)? as usize,None))),"path"=>{let (hops,confidence)=best_path(&adj,beliefs::id(req,"src")?,beliefs::id(req,"dst")?,None);Ok(json!({"hops":hops,"confidence":confidence}))},"paths"=>Ok(json!(simple_paths(&adj,beliefs::id(req,"src")?,beliefs::id(req,"dst")?,3,None,64)?)),_=>Err(Error::InvalidRequest)}
}
pub fn edge_insert(cfg:&Config,req:&Value,authority:&Authority)->Result<Value>{beliefs::require_write(authority)?;let mut conn=store::connect(cfg)?;let tx=conn.transaction_with_behavior(TransactionBehavior::Immediate)?;let sid=req["session_id"].as_str();let note=req["note"].as_str();let created=edge_insert_in_transaction(cfg,&tx,beliefs::id(req,"src")?,beliefs::id(req,"dst")?,beliefs::text(req,"rel",32)?,beliefs::text(req,"source",32)?,sid,note,authority)?;tx.commit()?;Ok(json!({"created":created}))}
pub fn backfill(cfg:&Config,_req:&Value,authority:&Authority)->Result<Value>{beliefs::require_write(authority)?;let mut conn=store::connect(cfg)?;let tx=conn.transaction_with_behavior(TransactionBehavior::Immediate)?;let mut stmt=tx.prepare("SELECT id,superseded_by FROM beliefs WHERE superseded_by IS NOT NULL")?;let rows=stmt.query_map([],|r|Ok((r.get::<_,i64>(0)?,r.get::<_,i64>(1)?)))?.collect::<std::result::Result<Vec<_>,_>>()?;drop(stmt);let mut changed=0;for (src,dst) in &rows{if edge_insert_in_transaction(cfg,&tx,*src,*dst,"supersedes","structural",None,Some("from beliefs.superseded_by"),authority)?{changed+=1}}tx.commit()?;Ok(json!({"supersedes":changed,"skipped":rows.len()-changed}))}

#[cfg(test)]mod tests{
    use super::*;
    #[test]fn best_path_uses_product_and_scope_is_not_a_relation_guess(){let adj=BTreeMap::from([(1,vec![Edge{dst:3,rel:"explains".into(),weight:0.1},Edge{dst:2,rel:"depends_on".into(),weight:0.8}]),(2,vec![Edge{dst:3,rel:"explains".into(),weight:0.8}])]);let (path,confidence)=best_path(&adj,1,3,None);assert_eq!(path.len(),2);assert!((confidence-0.64).abs()<1e-12);assert_eq!(khop(&adj,1,2,None)[&3],1);assert!(support_factor(500)<1.);assert_eq!(components(&adj,&BTreeSet::from([1,2,3,4])).len(),2)}
    #[test]fn assertion_support_is_distinct_session_and_projection_is_not_stored(){let authority=Authority::HumanReview{agent:"fixture".into(),engine:"unknown".into()};let temp=tempfile::tempdir_in("/home/docwilde/.cache/t").unwrap();let cfg=Config::for_root(temp.path().join("lore"));let a=beliefs::insert(&cfg,&json!({"subject":"user","claim":"a","confidence":0.8}),&authority).unwrap()["id"].as_i64().unwrap();let b=beliefs::insert(&cfg,&json!({"subject":"user","claim":"b","confidence":0.8}),&authority).unwrap()["id"].as_i64().unwrap();let req=json!({"src":a,"dst":b,"rel":"contradicts","source":"derived","session_id":"one"});assert_eq!(edge_insert(&cfg,&req,&authority).unwrap()["created"],true);assert_eq!(edge_insert(&cfg,&req,&authority).unwrap()["created"],false);let conn=store::connect(&cfg).unwrap();assert_eq!(edge_support(&conn,b,a,"contradicts").unwrap(),1);let (adj,_)=adjacency(&conn,None,&["active"],None,true).unwrap();assert_eq!(adj[&a][0].dst,b);assert!((adj[&a][0].weight-support_factor(1)).abs()<1e-12);}
    #[test]fn superseding_lower_endpoint_preserves_symmetric_assertion_support(){
        let temp=tempfile::tempdir_in("/home/docwilde/.cache/t").unwrap();let cfg=Config::for_root(temp.path().join("lore"));let authority=Authority::HumanReview{agent:"fixture".into(),engine:"unknown".into()};let mut ids=Vec::new();for claim in ["old","neighbor","survivor"]{ids.push(beliefs::insert(&cfg,&json!({"subject":"user","claim":claim,"confidence":0.8}),&authority).unwrap()["id"].as_i64().unwrap());}edge_insert(&cfg,&json!({"src":ids[0],"dst":ids[1],"rel":"contradicts","source":"derived","session_id":"one"}),&authority).unwrap();beliefs::supersede(&cfg,&json!({"belief_id":ids[0],"by":ids[2],"reason":"merge"}),&authority).unwrap();let conn=store::connect(&cfg).unwrap();assert_eq!(edge_support(&conn,ids[2],ids[1],"contradicts").unwrap(),1);assert_eq!(edge_support(&conn,ids[0],ids[1],"contradicts").unwrap(),0);let(adj,_)=adjacency(&conn,None,&["active"],None,false).unwrap();assert!(adj[&ids[2]].iter().any(|e|e.dst==ids[1]&&(e.weight-support_factor(1)).abs()<1e-12));
    }

}
